entity.modal_config.delete_form:
  path: '/admin/config/user-interface/modal-config/manage/{modal_config}/delete'
  defaults:
    _entity_form: 'modal_config.delete'
    _title: 'Delete shortcut set'
  requirements:
    _entity_access: 'modal_config.delete'

entity.modal_config.collection:
  path: '/admin/config/user-interface/modal-config'
  defaults:
    _entity_list: 'modal_config'
    _title: 'Modal configuration'
  requirements:
    _permission: 'administer shortcuts'

modal_config.set_add:
  path: '/admin/config/user-interface/modal-config/add-set'
  defaults:
    _entity_form: 'modal_config.add'
    _title: 'Add shortcut set'
  requirements:
    _entity_create_access: 'modal_config'

entity.modal_config.edit_form:
  path: '/admin/config/user-interface/modal-config/manage/{modal_config}'
  defaults:
    _entity_form: 'modal_config.edit'
    _title: 'Edit shortcut set'
  requirements:
    _entity_access: 'modal_config.update'

shortcut.link_add_inline:
  path: '/admin/config/user-interface/modal-config/manage/{modal_config}/add-link-inline'
  defaults:
    _controller: 'Drupal\modal_config\Controller\ModalConfigController::addShortcutLinkInline'
  requirements:
    _entity_access: 'modal_config.update'
    _csrf_token: 'TRUE'

entity.modal_config.customize_form:
  path: '/admin/config/user-interface/modal-config/manage/{modal_config}/customize'
  defaults:
    _entity_form: 'modal_config.customize'
    _title: 'List links'
  requirements:
    _entity_access: 'modal_config.update'

