entity.modal_config.delete_form:
  path: '/admin/config/user-interface/modal-config/manage/{modal_config}/delete'
  defaults:
    _entity_form: 'modal_config.delete'
    _title: 'Delete modal configuration'
  requirements:
    _entity_access: 'modal_config.delete'

entity.modal_config.collection:
  path: '/admin/config/user-interface/modal-config'
  defaults:
    _entity_list: 'modal_config'
    _title: 'Modal configuration'
  requirements:
    _permission: 'administer modal configuration'

modal_config.add:
  path: '/admin/config/user-interface/modal-config/add'
  defaults:
    _entity_form: 'modal_config.add'
    _title: 'Add modal configuration'
  requirements:
    _permission: 'administer modal configuration'

entity.modal_config.edit_form:
  path: '/admin/config/user-interface/modal-config/manage/{modal_config}'
  defaults:
    _entity_form: 'modal_config.edit'
    _title: 'Edit modal configuration'
  requirements:
    _entity_access: 'modal_config.update'
