# Schema for the configuration files of the Shortcut module.

modal_config.form.*:
  type: config_entity
  label: 'Modal configuration settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
